// Daily quiz questions — same question for all users on a given day
// Selected deterministically: dayOfYear % questions.length

const Q = [
  { fr: { q: "Quel film a remporté la Palme d'Or à Cannes en 2019 ?", o: ["Parasite", "Once Upon a Time in Hollywood", "Portrait de la jeune fille en feu", "Atlantique"], a: 0 }, en: { q: "Which film won the Palme d'Or at Cannes in 2019?", o: ["Parasite", "Once Upon a Time in Hollywood", "Portrait of a Lady on Fire", "Atlantics"], a: 0 } },
  { fr: { q: "Dans quelle ville se déroule la série 'Stranger Things' ?", o: ["Hawkins", "Springfield", "Riverdale", "Derry"], a: 0 }, en: { q: "In which town is 'Stranger Things' set?", o: ["Hawkins", "Springfield", "Riverdale", "Derry"], a: 0 } },
  { fr: { q: "Qui a composé la bande originale de 'Interstellar' ?", o: ["Hans Zimmer", "John Williams", "Ennio Morricone", "Howard Shore"], a: 0 }, en: { q: "Who composed the score for 'Interstellar'?", o: ["Hans Zimmer", "John Williams", "Ennio Morricone", "Howard Shore"], a: 0 } },
  { fr: { q: "Dans 'Attack on Titan', comment s'appelle le régiment d'élite d'Eren ?", o: ["Bataillon d'exploration", "Garde royale", "Légion des murs", "Armée du roi"], a: 0 }, en: { q: "In 'Attack on Titan', what is Eren's elite regiment called?", o: ["Survey Corps", "Royal Guard", "Wall Legion", "King's Army"], a: 0 } },
  { fr: { q: "Quel album de Daft Punk a popularisé 'Get Lucky' ?", o: ["Random Access Memories", "Discovery", "Homework", "Human After All"], a: 0 }, en: { q: "Which Daft Punk album featured 'Get Lucky'?", o: ["Random Access Memories", "Discovery", "Homework", "Human After All"], a: 0 } },
  { fr: { q: "Dans quel pays se passe l'action principale de 'Squid Game' ?", o: ["Corée du Sud", "Japon", "Chine", "Corée du Nord"], a: 0 }, en: { q: "In which country does 'Squid Game' primarily take place?", o: ["South Korea", "Japan", "China", "North Korea"], a: 0 } },
  { fr: { q: "Quel jeu vidéo se passe dans la cité de Rapture ?", o: ["BioShock", "Fallout 4", "Dishonored", "System Shock"], a: 0 }, en: { q: "Which video game is set in the city of Rapture?", o: ["BioShock", "Fallout 4", "Dishonored", "System Shock"], a: 0 } },
  { fr: { q: "Qui a écrit 'Harry Potter' ?", o: ["J.K. Rowling", "Tolkien", "Philip Pullman", "Roald Dahl"], a: 0 }, en: { q: "Who wrote 'Harry Potter'?", o: ["J.K. Rowling", "Tolkien", "Philip Pullman", "Roald Dahl"], a: 0 } },
  { fr: { q: "Dans 'Breaking Bad', quel est le surnom de Walter White ?", o: ["Heisenberg", "The One Who Knocks", "Danger", "El Diablo"], a: 0 }, en: { q: "In 'Breaking Bad', what is Walter White's alias?", o: ["Heisenberg", "The One Who Knocks", "Danger", "El Diablo"], a: 0 } },
  { fr: { q: "Quel manga se passe dans le monde de One Piece ?", o: ["One Piece", "Naruto", "Bleach", "Dragon Ball"], a: 0 }, en: { q: "Which manga is set in the world of One Piece?", o: ["One Piece", "Naruto", "Bleach", "Dragon Ball"], a: 0 } },
  { fr: { q: "Combien d'Oscars a remporté 'Le Seigneur des Anneaux : Le Retour du Roi' ?", o: ["11", "9", "13", "7"], a: 0 }, en: { q: "How many Oscars did 'The Lord of the Rings: The Return of the King' win?", o: ["11", "9", "13", "7"], a: 0 } },
  { fr: { q: "Quel acteur joue Tony Stark / Iron Man dans le MCU ?", o: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Jeremy Renner"], a: 0 }, en: { q: "Which actor plays Tony Stark / Iron Man in the MCU?", o: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Jeremy Renner"], a: 0 } },
  { fr: { q: "Dans 'Game of Thrones', qui est surnommé 'L'Araignée' ?", o: ["Varys", "Littlefinger", "Qyburn", "Theon"], a: 0 }, en: { q: "In 'Game of Thrones', who is nicknamed 'The Spider'?", o: ["Varys", "Littlefinger", "Qyburn", "Theon"], a: 0 } },
  { fr: { q: "Quel studio a créé 'The Legend of Zelda' ?", o: ["Nintendo", "Sega", "Capcom", "Square Enix"], a: 0 }, en: { q: "Which studio created 'The Legend of Zelda'?", o: ["Nintendo", "Sega", "Capcom", "Square Enix"], a: 0 } },
  { fr: { q: "Dans 'Death Note', quel est le vrai nom de Kira ?", o: ["Light Yagami", "L Lawliet", "Near", "Mello"], a: 0 }, en: { q: "In 'Death Note', what is Kira's real name?", o: ["Light Yagami", "L Lawliet", "Near", "Mello"], a: 0 } },
  { fr: { q: "Quel film de Studio Ghibli met en scène Chihiro ?", o: ["Le Voyage de Chihiro", "Princesse Mononoké", "Mon voisin Totoro", "Nausicaä"], a: 0 }, en: { q: "Which Studio Ghibli film features Chihiro?", o: ["Spirited Away", "Princess Mononoke", "My Neighbor Totoro", "Nausicaä"], a: 0 } },
  { fr: { q: "Quelle chanson ouvre l'album 'Thriller' de Michael Jackson ?", o: ["Wanna Be Startin' Somethin'", "Beat It", "Billie Jean", "Thriller"], a: 0 }, en: { q: "Which song opens Michael Jackson's 'Thriller' album?", o: ["Wanna Be Startin' Somethin'", "Beat It", "Billie Jean", "Thriller"], a: 0 } },
  { fr: { q: "Dans 'The Witcher', de quelle série de livres est adapté le jeu CD Projekt Red ?", o: ["Andrzej Sapkowski", "Joe Abercrombie", "George R.R. Martin", "Brandon Sanderson"], a: 0 }, en: { q: "The CD Projekt Red 'Witcher' game is based on books by whom?", o: ["Andrzej Sapkowski", "Joe Abercrombie", "George R.R. Martin", "Brandon Sanderson"], a: 0 } },
  { fr: { q: "Quel pays a réalisé le film 'Parasite' ?", o: ["Corée du Sud", "Japon", "Chine", "Taïwan"], a: 0 }, en: { q: "Which country produced the film 'Parasite'?", o: ["South Korea", "Japan", "China", "Taiwan"], a: 0 } },
  { fr: { q: "Dans 'Fullmetal Alchemist: Brotherhood', quelle loi fondamentale régit l'alchimie ?", o: ["Équivalence des échanges", "Conservation de la masse", "Loi de Murphy", "Principe d'Hermès"], a: 0 }, en: { q: "In 'Fullmetal Alchemist: Brotherhood', what fundamental law governs alchemy?", o: ["Equivalent Exchange", "Conservation of Mass", "Murphy's Law", "Hermes Principle"], a: 0 } },
  { fr: { q: "Quel auteur a écrit '1984' ?", o: ["George Orwell", "Aldous Huxley", "Ray Bradbury", "Philip K. Dick"], a: 0 }, en: { q: "Who wrote '1984'?", o: ["George Orwell", "Aldous Huxley", "Ray Bradbury", "Philip K. Dick"], a: 0 } },
  { fr: { q: "Quel film de Christopher Nolan se déroule dans les rêves ?", o: ["Inception", "Interstellar", "The Prestige", "Tenet"], a: 0 }, en: { q: "Which Christopher Nolan film takes place in dreams?", o: ["Inception", "Interstellar", "The Prestige", "Tenet"], a: 0 } },
  { fr: { q: "Dans quelle série trouve-t-on le personnage de Walter White ?", o: ["Breaking Bad", "Better Call Saul", "Ozark", "The Wire"], a: 0 }, en: { q: "In which series does Walter White appear?", o: ["Breaking Bad", "Better Call Saul", "Ozark", "The Wire"], a: 0 } },
  { fr: { q: "Quel groupe a enregistré l'album 'Dark Side of the Moon' ?", o: ["Pink Floyd", "Led Zeppelin", "The Beatles", "David Bowie"], a: 0 }, en: { q: "Which band recorded 'The Dark Side of the Moon'?", o: ["Pink Floyd", "Led Zeppelin", "The Beatles", "David Bowie"], a: 0 } },
  { fr: { q: "Dans 'Naruto', quel bijû est scellé dans Naruto ?", o: ["Kurama (Renard à 9 queues)", "Gyûki (Pieuvre à 8 queues)", "Shukaku (Sablier)", "Matatabi (Chat à 2 queues)"], a: 0 }, en: { q: "In 'Naruto', which Tailed Beast is sealed within Naruto?", o: ["Kurama (Nine-Tails Fox)", "Gyûki (Eight-Tails Octopus)", "Shukaku (Raccoon Dog)", "Matatabi (Two-Tails Cat)"], a: 0 } },
  { fr: { q: "Quel réalisateur a dirigé 'Pulp Fiction' ?", o: ["Quentin Tarantino", "Martin Scorsese", "Coen Brothers", "David Fincher"], a: 0 }, en: { q: "Who directed 'Pulp Fiction'?", o: ["Quentin Tarantino", "Martin Scorsese", "Coen Brothers", "David Fincher"], a: 0 } },
  { fr: { q: "Dans 'The Last of Us', comment s'appelle le champignon qui infecte les humains ?", o: ["Cordyceps", "Clicker", "Runner", "Bloater"], a: 0 }, en: { q: "In 'The Last of Us', what is the fungus that infects humans called?", o: ["Cordyceps", "Clicker", "Runner", "Bloater"], a: 0 } },
  { fr: { q: "Quel artiste a sorti l'album 'To Pimp a Butterfly' ?", o: ["Kendrick Lamar", "J. Cole", "Drake", "Kanye West"], a: 0 }, en: { q: "Which artist released 'To Pimp a Butterfly'?", o: ["Kendrick Lamar", "J. Cole", "Drake", "Kanye West"], a: 0 } },
  { fr: { q: "Dans 'Demon Slayer', quelle technique Tanjiro maîtrise-t-il en premier ?", o: ["Respiration de l'eau", "Respiration du feu", "Respiration de la lune", "Respiration du tonnerre"], a: 0 }, en: { q: "In 'Demon Slayer', which breathing technique does Tanjiro first master?", o: ["Water Breathing", "Flame Breathing", "Moon Breathing", "Thunder Breathing"], a: 0 } },
  { fr: { q: "Quel roman a inspiré la série 'The Handmaid's Tale' ?", o: ["Margaret Atwood", "Donna Tartt", "Gillian Flynn", "Toni Morrison"], a: 0 }, en: { q: "'The Handmaid's Tale' series is based on a novel by whom?", o: ["Margaret Atwood", "Donna Tartt", "Gillian Flynn", "Toni Morrison"], a: 0 } },
  { fr: { q: "Quel jeu a popularisé le terme 'battle royale' dans les jeux vidéo ?", o: ["PUBG", "Fortnite", "Apex Legends", "H1Z1"], a: 0 }, en: { q: "Which game popularized the term 'battle royale' in gaming?", o: ["PUBG", "Fortnite", "Apex Legends", "H1Z1"], a: 0 } },
  { fr: { q: "Dans 'Cowboy Bebop', quel est le vaisseau de l'équipage ?", o: ["Bebop", "Swordfish II", "Red Tail", "Hammerhead"], a: 0 }, en: { q: "In 'Cowboy Bebop', what is the crew's ship called?", o: ["Bebop", "Swordfish II", "Red Tail", "Hammerhead"], a: 0 } },
  { fr: { q: "Quel film a inauguré l'Univers Cinématographique Marvel en 2008 ?", o: ["Iron Man", "The Incredible Hulk", "Thor", "Captain America"], a: 0 }, en: { q: "Which film launched the Marvel Cinematic Universe in 2008?", o: ["Iron Man", "The Incredible Hulk", "Thor", "Captain America"], a: 0 } },
  { fr: { q: "Quel auteur a créé le personnage de Sherlock Holmes ?", o: ["Arthur Conan Doyle", "Agatha Christie", "Edgar Allan Poe", "G.K. Chesterton"], a: 0 }, en: { q: "Who created the character Sherlock Holmes?", o: ["Arthur Conan Doyle", "Agatha Christie", "Edgar Allan Poe", "G.K. Chesterton"], a: 0 } },
  { fr: { q: "Dans 'Dragon Ball Z', quelle est la transformation ultime de Goku ?", o: ["Super Saiyan God", "Super Saiyan Blue", "Ultra Instinct", "Super Saiyan 4"], a: 2 }, en: { q: "In 'Dragon Ball Z', what is Goku's ultimate transformation?", o: ["Super Saiyan God", "Super Saiyan Blue", "Ultra Instinct", "Super Saiyan 4"], a: 2 } },
  { fr: { q: "Quel groupe a sorti l'album 'OK Computer' ?", o: ["Radiohead", "Portishead", "Massive Attack", "Björk"], a: 0 }, en: { q: "Which band released 'OK Computer'?", o: ["Radiohead", "Portishead", "Massive Attack", "Björk"], a: 0 } },
  { fr: { q: "Dans 'Blade Runner 2049', qui joue K ?", o: ["Ryan Gosling", "Harrison Ford", "Jared Leto", "Dave Bautista"], a: 0 }, en: { q: "In 'Blade Runner 2049', who plays K?", o: ["Ryan Gosling", "Harrison Ford", "Jared Leto", "Dave Bautista"], a: 0 } },
  { fr: { q: "Quel jeu FromSoftware a popularisé le genre 'Soulslike' ?", o: ["Demon's Souls", "Dark Souls", "Bloodborne", "Elden Ring"], a: 0 }, en: { q: "Which FromSoftware game popularized the 'Soulslike' genre?", o: ["Demon's Souls", "Dark Souls", "Bloodborne", "Elden Ring"], a: 0 } },
  { fr: { q: "Dans 'Hunter x Hunter', quelle est la capacité de Gon ?", o: ["Nen", "Chakra", "Reiatsu", "Ki"], a: 0 }, en: { q: "In 'Hunter x Hunter', what is the name of the life energy power system?", o: ["Nen", "Chakra", "Reiatsu", "Ki"], a: 0 } },
  { fr: { q: "Quel roman dystopique décrit un monde où les livres sont brûlés ?", o: ["Fahrenheit 451", "Le Meilleur des Mondes", "1984", "La Route"], a: 0 }, en: { q: "Which dystopian novel depicts a world where books are burned?", o: ["Fahrenheit 451", "Brave New World", "1984", "The Road"], a: 0 } },
  { fr: { q: "Dans quelle ville se passe 'The Wire' ?", o: ["Baltimore", "New York", "Chicago", "Philadelphia"], a: 0 }, en: { q: "In which city is 'The Wire' set?", o: ["Baltimore", "New York", "Chicago", "Philadelphia"], a: 0 } },
  { fr: { q: "Quel artiste a sorti 'Purple Rain' ?", o: ["Prince", "David Bowie", "Michael Jackson", "Stevie Wonder"], a: 0 }, en: { q: "Which artist released 'Purple Rain'?", o: ["Prince", "David Bowie", "Michael Jackson", "Stevie Wonder"], a: 0 } },
  { fr: { q: "Dans 'Neon Genesis Evangelion', comment s'appelle l'organisation qui pilote les EVA ?", o: ["NERV", "SEELE", "WILLE", "GEHIRN"], a: 0 }, en: { q: "In 'Neon Genesis Evangelion', what is the organization that operates the EVA units called?", o: ["NERV", "SEELE", "WILLE", "GEHIRN"], a: 0 } },
  { fr: { q: "Quel film de David Fincher met en scène un tueur en série traquant selon les 7 péchés capitaux ?", o: ["Se7en", "Zodiac", "Mindhunter", "Gone Girl"], a: 0 }, en: { q: "Which David Fincher film features a serial killer targeting the 7 deadly sins?", o: ["Se7en", "Zodiac", "Mindhunter", "Gone Girl"], a: 0 } },
  { fr: { q: "Quel studio japonais a développé 'Final Fantasy' ?", o: ["Square Enix", "Capcom", "Konami", "Bandai Namco"], a: 0 }, en: { q: "Which Japanese studio developed 'Final Fantasy'?", o: ["Square Enix", "Capcom", "Konami", "Bandai Namco"], a: 0 } },
  { fr: { q: "Dans 'One Piece', comment s'appelle l'équipage de Luffy ?", o: ["Équipage du Chapeau de Paille", "Équipage des Pirates Noirs", "Équipage des 100 Bêtes", "Équipage de l'Île du Trésor"], a: 0 }, en: { q: "In 'One Piece', what is Luffy's crew called?", o: ["Straw Hat Pirates", "Blackbeard Pirates", "Beasts Pirates", "Treasure Island Crew"], a: 0 } },
  { fr: { q: "Quel film de Stanley Kubrick se passe en grande partie dans un hôtel isolé ?", o: ["Shining", "2001", "Full Metal Jacket", "Eyes Wide Shut"], a: 0 }, en: { q: "Which Stanley Kubrick film is largely set in a remote hotel?", o: ["The Shining", "2001", "Full Metal Jacket", "Eyes Wide Shut"], a: 0 } },
  { fr: { q: "Quel album de Kendrick Lamar a remporté le Prix Pulitzer 2018 ?", o: ["DAMN.", "To Pimp a Butterfly", "good kid, m.A.A.d city", "Mr. Morale"], a: 0 }, en: { q: "Which Kendrick Lamar album won the 2018 Pulitzer Prize?", o: ["DAMN.", "To Pimp a Butterfly", "good kid, m.A.A.d city", "Mr. Morale"], a: 0 } },
  { fr: { q: "Dans 'Mob Psycho 100', quel est le vrai prénom de Mob ?", o: ["Shigeo", "Reigen", "Ritsu", "Dimple"], a: 0 }, en: { q: "In 'Mob Psycho 100', what is Mob's real first name?", o: ["Shigeo", "Reigen", "Ritsu", "Dimple"], a: 0 } },
  { fr: { q: "Qui a réalisé 'No Country for Old Men' ?", o: ["Coen Brothers", "David Fincher", "Denis Villeneuve", "Paul Thomas Anderson"], a: 0 }, en: { q: "Who directed 'No Country for Old Men'?", o: ["Coen Brothers", "David Fincher", "Denis Villeneuve", "Paul Thomas Anderson"], a: 0 } },
  { fr: { q: "Dans 'The Mandalorian', comment les fans surnomment-ils le personnage de Grogu ?", o: ["Baby Yoda", "Mini Yoda", "Tiny Jedi", "Little Green"], a: 0 }, en: { q: "In 'The Mandalorian', what do fans call Grogu?", o: ["Baby Yoda", "Mini Yoda", "Tiny Jedi", "Little Green"], a: 0 } },
  { fr: { q: "Quel jeu vidéo open-world se passe dans Night City ?", o: ["Cyberpunk 2077", "Watch Dogs Legion", "Deus Ex: Mankind Divided", "Observer"], a: 0 }, en: { q: "Which open-world game is set in Night City?", o: ["Cyberpunk 2077", "Watch Dogs Legion", "Deus Ex: Mankind Divided", "Observer"], a: 0 } },
  { fr: { q: "Quel auteur a écrit 'Le Nom de la Rose' ?", o: ["Umberto Eco", "Jorge Luis Borges", "Gabriel García Márquez", "Italo Calvino"], a: 0 }, en: { q: "Who wrote 'The Name of the Rose'?", o: ["Umberto Eco", "Jorge Luis Borges", "Gabriel García Márquez", "Italo Calvino"], a: 0 } },
  { fr: { q: "Dans 'Vinland Saga', qui est le père adoptif de Thorfinn ?", o: ["Askeladd", "Thors", "Canute", "Bjorn"], a: 0 }, en: { q: "In 'Vinland Saga', who is Thorfinn's adoptive father figure?", o: ["Askeladd", "Thors", "Canute", "Bjorn"], a: 0 } },
  { fr: { q: "Quel film a lancé la carrière de Wes Anderson ?", o: ["Bottle Rocket", "Rushmore", "The Royal Tenenbaums", "The Life Aquatic"], a: 0 }, en: { q: "Which film launched Wes Anderson's career?", o: ["Bottle Rocket", "Rushmore", "The Royal Tenenbaums", "The Life Aquatic"], a: 0 } },
  { fr: { q: "Quel groupe a sorti l'album 'Nevermind' en 1991 ?", o: ["Nirvana", "Pearl Jam", "Soundgarden", "Alice in Chains"], a: 0 }, en: { q: "Which band released 'Nevermind' in 1991?", o: ["Nirvana", "Pearl Jam", "Soundgarden", "Alice in Chains"], a: 0 } },
  { fr: { q: "Dans 'Jujutsu Kaisen', quel est le nom de la malédiction scellée dans Yuji Itadori ?", o: ["Ryomen Sukuna", "Mahito", "Geto Suguru", "Hanami"], a: 0 }, en: { q: "In 'Jujutsu Kaisen', what is the name of the curse sealed inside Yuji Itadori?", o: ["Ryomen Sukuna", "Mahito", "Geto Suguru", "Hanami"], a: 0 } },
  { fr: { q: "Qui joue Hannibal Lecter dans 'Le Silence des Agneaux' ?", o: ["Anthony Hopkins", "Brian Cox", "Mads Mikkelsen", "Richard Gere"], a: 0 }, en: { q: "Who plays Hannibal Lecter in 'The Silence of the Lambs'?", o: ["Anthony Hopkins", "Brian Cox", "Mads Mikkelsen", "Richard Gere"], a: 0 } },
  { fr: { q: "Quel jeu de Nintendo a popularisé le gaming mobile ?", o: ["Pokémon GO", "Mario Kart Tour", "Animal Crossing Pocket Camp", "Fire Emblem Heroes"], a: 0 }, en: { q: "Which Nintendo game popularized mobile gaming?", o: ["Pokémon GO", "Mario Kart Tour", "Animal Crossing Pocket Camp", "Fire Emblem Heroes"], a: 0 } },
  { fr: { q: "Dans 'Berserk', quel est l'ennemi récurrent et ancien ami de Guts ?", o: ["Griffith", "Zodd", "Femto", "Slan"], a: 0 }, en: { q: "In 'Berserk', who is Guts's recurring enemy and former friend?", o: ["Griffith", "Zodd", "Femto", "Slan"], a: 0 } },
  { fr: { q: "Quel film de Denis Villeneuve a remporté 6 Oscars en 2022 ?", o: ["Dune", "Blade Runner 2049", "Arrival", "Sicario"], a: 0 }, en: { q: "Which Denis Villeneuve film won 6 Oscars in 2022?", o: ["Dune", "Blade Runner 2049", "Arrival", "Sicario"], a: 0 } },
  { fr: { q: "Quelle série Netflix se passe dans un cabinet d'avocats de Séoul ?", o: ["Extraordinary Attorney Woo", "My Mister", "Signal", "Kingdom"], a: 0 }, en: { q: "Which Netflix series is set in a Seoul law firm?", o: ["Extraordinary Attorney Woo", "My Mister", "Signal", "Kingdom"], a: 0 } },
  { fr: { q: "Qui a réalisé 'Oldboy' (2003) ?", o: ["Park Chan-wook", "Bong Joon-ho", "Kim Jee-woon", "Lee Chang-dong"], a: 0 }, en: { q: "Who directed 'Oldboy' (2003)?", o: ["Park Chan-wook", "Bong Joon-ho", "Kim Jee-woon", "Lee Chang-dong"], a: 0 } },
]

export function getTodayQuestion() {
  const now = new Date()
  const start = new Date(now.getFullYear(), 0, 0)
  const diff = now - start
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24))
  return Q[dayOfYear % Q.length]
}

export function getTodayKey() {
  const now = new Date()
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`
}
